// <auto-generated />
using System;
using AppointmentBooking.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppointmentBooking.DAL.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20260324105033_FinalDB")]
    partial class FinalDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppointmentBooking.DAL.Entity.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("TimeSlot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("AppointmentBooking.DAL.Entity.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string>("AvailableDays")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ConsultationFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Specialization")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableDays = "[1,3]",
                            ConsultationFee = 500.0m,
                            Name = "Shyam",
                            Specialization = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            AvailableDays = "[2,5]",
                            ConsultationFee = 1500.0m,
                            Name = "Raju",
                            Specialization = 5,
                            UserId = 4
                        },
                        new
                        {
                            Id = 3,
                            AvailableDays = "[1,3]",
                            ConsultationFee = 500.0m,
                            Name = "charli",
                            Specialization = 4,
                            UserId = 6
                        },
                        new
                        {
                            Id = 4,
                            AvailableDays = "[1,5]",
                            ConsultationFee = 300.0m,
                            Name = "Fortis",
                            Specialization = 3,
                            UserId = 8
                        },
                        new
                        {
                            Id = 5,
                            AvailableDays = "[1,6]",
                            ConsultationFee = 800.0m,
                            Name = "Chabra",
                            Specialization = 5,
                            UserId = 9
                        });
                });

            modelBuilder.Entity("AppointmentBooking.DAL.Entity.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 20,
                            Name = "Mohan",
                            PhoneNumber = "99999999999",
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            Age = 22,
                            Name = "Jiwan",
                            PhoneNumber = "99999999999",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Age = 28,
                            Name = "raja",
                            PhoneNumber = "99999999999",
                            UserId = 5
                        },
                        new
                        {
                            Id = 4,
                            Age = 20,
                            Name = "ranga",
                            PhoneNumber = "99999999999",
                            UserId = 7
                        });
                });

            modelBuilder.Entity("AppointmentBooking.DAL.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "jiwan@gmail.com",
                            IsAdmin = false,
                            Password = "Jiwan@123"
                        },
                        new
                        {
                            Id = 2,
                            Email = "shyam@gmail.com",
                            IsAdmin = true,
                            Password = "Shyam@123"
                        },
                        new
                        {
                            Id = 3,
                            Email = "mohan@gmail.com",
                            IsAdmin = false,
                            Password = "Mohan@123"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Raju@gmail.com",
                            IsAdmin = true,
                            Password = "Raju@123"
                        },
                        new
                        {
                            Id = 5,
                            Email = "raja@gmail.com",
                            IsAdmin = false,
                            Password = "Raja@123"
                        },
                        new
                        {
                            Id = 6,
                            Email = "charli@gmail.com",
                            IsAdmin = true,
                            Password = "Charli@123"
                        },
                        new
                        {
                            Id = 7,
                            Email = "ranga@gmail.com",
                            IsAdmin = false,
                            Password = "Ranga@123"
                        },
                        new
                        {
                            Id = 8,
                            Email = "fortis@gmail.com",
                            IsAdmin = true,
                            Password = "Fortis@123"
                        },
                        new
                        {
                            Id = 9,
                            Email = "chabra@gmail.com",
                            IsAdmin = true,
                            Password = "Chabra@123"
                        });
                });

            modelBuilder.Entity("AppointmentBooking.DAL.Entity.Appointment", b =>
                {
                    b.HasOne("AppointmentBooking.DAL.Entity.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AppointmentBooking.DAL.Entity.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("AppointmentBooking.DAL.Entity.Doctor", b =>
                {
                    b.HasOne("AppointmentBooking.DAL.Entity.User", "User")
                        .WithOne("Doctor")
                        .HasForeignKey("AppointmentBooking.DAL.Entity.Doctor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AppointmentBooking.DAL.Entity.Patient", b =>
                {
                    b.HasOne("AppointmentBooking.DAL.Entity.User", "User")
                        .WithOne("Patient")
                        .HasForeignKey("AppointmentBooking.DAL.Entity.Patient", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AppointmentBooking.DAL.Entity.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("AppointmentBooking.DAL.Entity.Patient", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("AppointmentBooking.DAL.Entity.User", b =>
                {
                    b.Navigation("Doctor")
                        .IsRequired();

                    b.Navigation("Patient")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
